source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.28.0'
gem 'concurrent-ruby', '< 1.3.6'

# connection_pool 3.x (pulled in transitively by activesupport) requires
# Ruby >= 3.2. Staying on the 2.x line keeps this sample installable on the
# Ruby baseline the `ruby` directive above advertises.
gem 'connection_pool', '< 3.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
