//
// Copyright (C) 2026 Acoustic, L.P. All rights reserved.
//
// NOTICE: This file contains material that is confidential and proprietary to
// Acoustic, L.P. and/or other developers. No license is granted under any
// intellectual or industrial property rights of Acoustic, L.P. except as may
// be provided in an agreement with Acoustic, L.P. Any unauthorized copying or
// distribution of content from this file is prohibited.
//
// Generated by react-native-acoustic-connect Expo Config Plugin.
// Canonical reference: Examples/bare-workflow/ios/ConnectNCE/NotificationViewController.swift
// The CONNECT_APP_GROUP_IDENTIFIER_PLACEHOLDER token is replaced by the plugin
// with the resolved App Group identifier from ConnectConfig.json (or the
// iosAppGroupIdentifier plugin prop in app.json).
//

import Connect

// Notification Content Extension principal class — referenced by
// `NSExtensionPrincipalClass` in this target's Info.plist.
//
// The whole implementation is inherited from
// `ConnectNotificationContentExtension` (Connect SDK): it renders the rich
// expansion UI (media attachment and/or expanded body) below the system
// banner when the user long-presses / expands an Acoustic notification.
//
// As with the NSE, the only host responsibility is to point the extension at
// the SAME App Group as the host app and the NSE so all three processes
// read/write the same pending store. Mirrors the iOS-SDK NCE reference 1:1.
final class NotificationViewController: ConnectNotificationContentExtension {
    override var appGroupIdentifier: String? {
        "CONNECT_APP_GROUP_IDENTIFIER_PLACEHOLDER"
    }
}
