// Copyright (C) 2026 Acoustic, L.P. All rights reserved.
//
// Unit tests for the pure helpers in plugin/src/withConnectNSE.ts.
// Uses Node's built-in test runner (node:test) against the compiled CommonJS
// output in plugin/build — no Jest / extra dependency required.
//
//   npm run test:plugin   (builds first, then runs)

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'

const require = createRequire(import.meta.url)
const nse = require('../build/withConnectNSE.js')

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'connect-nse-test-'))
}

// ─── assertValidAppGroup ───────────────────────────────────────────────────

test('assertValidAppGroup accepts a well-formed identifier', () => {
  assert.equal(
    nse.assertValidAppGroup('group.com.example.app', 'test'),
    'group.com.example.app'
  )
})

test('assertValidAppGroup rejects a value without the group. prefix', () => {
  assert.throws(() => nse.assertValidAppGroup('com.example.app', 'test'), /Invalid iOS App Group/)
})

test('assertValidAppGroup rejects XML-injection characters', () => {
  assert.throws(
    () => nse.assertValidAppGroup('group.com</string><foo>', 'test'),
    /Invalid iOS App Group/
  )
})

// ─── resolveAppGroupIdentifier ──────────────────────────────────────────────

test('resolveAppGroupIdentifier: plugin prop wins over ConnectConfig.json', () => {
  const dir = tmpDir()
  fs.writeFileSync(
    path.join(dir, 'ConnectConfig.json'),
    JSON.stringify({ Connect: { iOSAppGroupIdentifier: 'group.from.config' } })
  )
  assert.equal(
    nse.resolveAppGroupIdentifier(dir, { iosAppGroupIdentifier: 'group.from.prop' }),
    'group.from.prop'
  )
})

test('resolveAppGroupIdentifier: falls back to ConnectConfig.json', () => {
  const dir = tmpDir()
  fs.writeFileSync(
    path.join(dir, 'ConnectConfig.json'),
    JSON.stringify({ Connect: { iOSAppGroupIdentifier: 'group.from.config' } })
  )
  assert.equal(nse.resolveAppGroupIdentifier(dir, {}), 'group.from.config')
})

test('resolveAppGroupIdentifier: throws when neither source provides a value', () => {
  const dir = tmpDir() // no ConnectConfig.json
  assert.throws(
    () => nse.resolveAppGroupIdentifier(dir, {}),
    /Could not resolve iOS App Group/
  )
})

test('resolveAppGroupIdentifier: throws on malformed ConnectConfig value', () => {
  const dir = tmpDir()
  fs.writeFileSync(
    path.join(dir, 'ConnectConfig.json'),
    JSON.stringify({ Connect: { iOSAppGroupIdentifier: 'not-a-group' } })
  )
  assert.throws(() => nse.resolveAppGroupIdentifier(dir, {}), /Invalid iOS App Group/)
})

// ─── substituteSwiftTemplate ────────────────────────────────────────────────

test('substituteSwiftTemplate replaces EVERY placeholder and prepends header', () => {
  const dir = tmpDir()
  const tpl = path.join(dir, 'NotificationService.swift')
  // Placeholder appears twice (comment + code) — both must be replaced.
  fs.writeFileSync(
    tpl,
    '// see CONNECT_APP_GROUP_IDENTIFIER_PLACEHOLDER\nreturn "CONNECT_APP_GROUP_IDENTIFIER_PLACEHOLDER"\n'
  )
  const out = nse.substituteSwiftTemplate(tpl, 'group.com.example.app')
  assert.match(out, /^\/\/ @generated by react-native-acoustic-connect/)
  assert.equal(out.includes('CONNECT_APP_GROUP_IDENTIFIER_PLACEHOLDER'), false)
  assert.equal((out.match(/group\.com\.example\.app/g) || []).length, 2)
})

// ─── plist builders ─────────────────────────────────────────────────────────

test('buildNSEInfoPlist declares the user-notifications service extension point', () => {
  const plist = nse.buildNSEInfoPlist()
  assert.match(plist, /com\.apple\.usernotifications\.service/)
  assert.match(plist, /\$\(PRODUCT_MODULE_NAME\)\.NotificationService/)
})

test('buildNSEEntitlements embeds the app group', () => {
  const ent = nse.buildNSEEntitlements('group.com.example.app')
  assert.match(ent, /com\.apple\.security\.application-groups/)
  assert.match(ent, /<string>group\.com\.example\.app<\/string>/)
})

// ─── Podfile injection ──────────────────────────────────────────────────────

test('buildPodfileBlock contains the marker and ConnectNSE target', () => {
  const block = nse.buildPodfileBlock()
  assert.match(block, /@generated ConnectNSE target/)
  assert.match(block, /target 'ConnectNSE' do/)
})

test('injectPodfileBlock is idempotent', () => {
  const base = "platform :ios, '15.1'\n"
  const once = nse.injectPodfileBlock(base)
  const twice = nse.injectPodfileBlock(once)
  assert.equal(once, twice, 're-injection must be a no-op')
  assert.equal((once.match(/target 'ConnectNSE' do/g) || []).length, 1)
})
